### ISSUE TITLE
Sector codelist error 

### ISSUE THREAD

**Issue by siwhitehouse** [pwyf/data-quality-tester#35]
Publish What You Fund have received the following email:

> Hi,
> 
> We are testing our activity file against the PWYF data quality tester and we are getting an error on sector code (see screenshot below). The case seems to be unique for sector code 43060, which is present in the IATI sector code list. Hope you can help us with this issue.
> 
> Thank you.
> 
> ![errorMsg](https://user-images.githubusercontent.com/1718090/60754306-453e3300-9fd7-11e9-8b65-ca3e5f2a9024.png)
>  
> 
> Regards,
> 
> -Lulu
> 
> Consultant
> 
> SPOP- Asian Development Bank

Lulu references http://reference.iatistandard.org/203/codelists/Sector/ which is the replicated DAC 5 digit sector codelist and includes the code '43060': "Disaster Risk Reduction".

**Comment by siwhitehouse** [comment]
Neither https://raw.githubusercontent.com/pwyf/data-quality-tester/develop/codelists/1/Sector.json and https://raw.githubusercontent.com/pwyf/data-quality-tester/develop/codelists/2/Sector.json contain a code '43060' (note: I'm not certain this where the DQT checks sample files against IATI codelists).

The /develop/codelists folder's last commit was on 14 Dec 2017.

Each of those Sector codelists files have the following metadata 

"metadata": {"url": "http://www.oecd.org/dac/stats/dacandcrscodelists.htm", "name": "DAC 5 Digit Sector"

Checking the file at https://webfs.oecd.org/crs-iati-xml/Lookup/DAC-CRS-CODES.xml I can see a code for '43060'. 

My initial best guess is that the codelists need to be brought up to date with the latest version of the 5 digit DAC codes that are implemeted by IATI.

**Comment by andylolz** [comment]
> My initial best guess is that the codelists need to be brought up to date with the latest version of the 5 digit DAC codes that are implemeted by IATI.

I think you’re right.

Looks like I added this codelist code to IATI (IATI/IATI-Codelists-NonEmbedded#283) but forgot to update it in the DQT.

There’s a flask command to do this, but doesn’t seem to be working at the moment.

**Comment by andylolz** [comment]
Okay, `flask refresh-codelists` works now, so I’ll leave this with you.

**Comment by siwhitehouse** [comment]
This fix has been applied on the DQT server and the file that Lulu was testing no longer causes an error.
