### ISSUE TITLE
Unable to test IATI file: TypeError: 'bool' object is not subscriptable in tasks.py

### ISSUE THREAD

**Issue by siwhitehouse** [pwyf/data-quality-tester#37]
I would like to review #36

I have tried to test the proposed fix locally, but I am having difficulties with running the DQT.

I followed the instructions at https://github.com/pwyf/data-quality-tester, which required some updates to be run afterwards.

Once the DQT loaded locally, attempting to test a file resulted in the following error:

> `FileNotFoundError: [Errno 2] No such file or directory: '/home/simon/code/data-quality-tester/2018-index-indicator-definitions/test_definitions/performance/../step_definitions.py'`

I cloned the 2018-index-indicator-definitions repo into the data-quality-tester folder and now when I try and load an IATI activity file I am getting the following error message instead:

```
>   File "/home/simon/code/data-quality-tester/DataQualityTester/tasks.py", line 119, in test_file_task
    result[lookup.get(out[0])] += 1
TypeError: 'bool' object is not subscriptable
```
The front-end hangs with this error.

**Comment by siwhitehouse** [comment]
http://d-portal.org/q.xml?aid=46004-39295-013-LN3142 is an example of a file that produces this issue. I have tried using both the download and the link function of the DQT.

**Comment by andylolz** [comment]
#28 is probably worthwhile.

I added celery to make the DQT handle bigger files, but it might be preferable to just strip it out.

**Comment by siwhitehouse** [comment]
The merge referenced above has fixed the celery error.
